#!/usr/bin/env bash

sudo apt-get install build-essential wget -y
wget --no-check-certificate -N https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
cd libsodium*
./configure
make -j8 && make install
echo /usr/local/lib > /etc/ld.so.conf.d/usr_local_lib.conf
ldconfig
